FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-build

WORKDIR /usr/src/app

RUN install_packages \
      alsa-utils \
      festival \
      festvox-kallpc16k \
      festvox-don \
      festvox-rablpc16k

COPY package.json .
RUN npm install

COPY index.js .
COPY start.sh .

CMD ["bash", "start.sh"]
